include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    snippet: studio_5col
    artifact-name: aurora_corne_left_5col
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
    snippet: studio_5col
    artifact-name: aurora_corne_right_5col
