include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    artifact-name: aurora_corne_5col_left
    extra-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne5x3\"
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
    artifact-name: aurora_corne_5col_right
    extra-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Corne5x3\"
